- menu_name: "Services"

- name: "Kontakt"
  url: "/kontakt/"
  title: "Kontakt"

# - name: "RSS"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: ""

# - name: "sitemap"
#   url: "/sitemap.xml"
#   title: "Site"
